name = "TransitionIndicators"
uuid = "5f5b98ec-1183-43e0-887a-12fdc55c52f7"
authors = ["Jan Swierczek-Jereczek <jan.jereczek@gmail.com>", "George Datseris <datseris.george@gmail.com>"]
version = "0.1.0"
